### ISSUE TITLE
[UserManagement] StreamReader=>ReadAllText

### ISSUE THREAD

**Issue by SlejmUr** [papershredder432/SPT-ModManager#1]
Here:

https://github.com/papershredder432/SPT-ModManager/blob/9e2fd36b9d1bfdf8ef028eb856431372dba97027/src/SPT-Manager/API/UserManager.cs#L19

Can be shortened to
```
var r = JsonConvert.DeserializeObject<dynamic>(File.ReadAllText(p));
```
(Or ReadAllTexts idk)

**Comment by SlejmUr** [comment]
Also you can use
```cs
                users.Add(new User
                {
                    Username = username,
                    UserId = userid,
                    DefaultPack = ""
                });
```

;)

**Comment by papershredder432** [comment]
I'm well aware, but I do this for the sake of my readability.
